#!/usr/bin/env ruby
require 'fileutils'
require 'open-uri'

git_bundles = %w[
  wincent/Command-T
  keithbsmiley/rspec.vim
  ap/vim-css-color
  bkad/CamelCaseMotion
  bling/vim-airline
  briancollins/vim-jst
  cakebaker/scss-syntax.vim
  elzr/vim-json
  kchmck/vim-coffee-script
  scrooloose/nerdcommenter
  scrooloose/nerdtree
  scrooloose/syntastic
  slim-template/vim-slim
  sstephenson/eco
  tpope/vim-endwise
  tpope/vim-fugitive
  tpope/vim-rhubarb
  tpope/vim-haml
  tpope/vim-rails
  tpope/vim-surround
  tpope/vim-unimpaired
  vim-ruby/vim-ruby
  vim-scripts/grep.vim
  sjbach/lusty
  rking/ag.vim
  mhinz/vim-hugefile
  jeetsukumaran/vim-buffergator
  digitaltoad/vim-pug
  airblade/vim-gitgutter
  easymotion/vim-easymotion
  flazz/vim-colorschemes
  int3/vim-extradite
  posva/vim-vue
]

git_keep = []

bundles_dir = File.join(File.dirname(__FILE__), 'bundle')

FileUtils.mkdir bundles_dir unless File.exists?(bundles_dir)
FileUtils.cd(bundles_dir)

puts "trashing everything..."
Dir['*'].each {|d| FileUtils.rm_rf d unless git_keep.include?(d) }

puts "fetching plugins..."
git_bundles.each do |plugin|
  url = "git://github.com/#{plugin}"
  dir = url.split('/').last

  puts "  Unpacking #{url} into #{dir}"
  %x{git clone #{url} #{dir}}
end

puts "compiling command-t..."

environment = 'ARCHFLAGS="-Wno-error=unused-command-line-argument-hard-error-in-future"'
command_t_path = File.join 'Command-T/ruby/command-t'
rvm_init_script = 'source $HOME/.zshrc && rvm use ruby-2.0.0-p645'
command_t_build_script = 'bundle && ruby extconf.rb && make'
# command_t_build_script = 'bundle && make clean && ruby extconf.rb && make'
puts %x{zsh -c 'cd #{command_t_path} && #{rvm_init_script} && #{environment} #{command_t_build_script}'}
