#!/usr/bin/env ruby
require 'fileutils'
require 'open-uri'

git_bundles = [
  'git://github.com/tpope/vim-fugitive',
  'git://github.com/scrooloose/nerdtree',
  'git://github.com/tpope/vim-unimpaired', # для переходов по содержимому quicklist http://www.vim.org/scripts/script.php?script_id=1590
  #'git://github.com/timcharper/textile.vim',
  #'git://github.com/tpope/vim-cucumber',
  #'git://github.com/tpope/vim-git',
  #'git://github.com/tpope/vim-markdown',
  'git://github.com/vim-ruby/vim-ruby',
  'git://github.com/tpope/vim-rails',
  'git://github.com/scrooloose/nerdcommenter',
  #'git://github.com/tpope/vim-repeat',
  'git://github.com/tpope/vim-surround',
  #'git://github.com/tpope/vim-vividchalk',
  #'git://github.com/tsaleh/vim-align',
  #'git://github.com/tsaleh/vim-shoulda',
  #'git://github.com/tsaleh/vim-supertab',
  #'git://github.com/tsaleh/vim-tcomment',
  'git://github.com/cakebaker/scss-syntax.vim',
  'git://github.com/majutsushi/tagbar',
  'git://github.com/jeetsukumaran/vim-buffergator',
  'git://github.com/tpope/vim-haml',
  'git://github.com/slim-template/vim-slim',
  'git://github.com/ap/vim-css-color',
  'git://github.com/kchmck/vim-coffee-script',
  'git://github.com/briancollins/vim-jst',
  'git://github.com/sstephenson/eco',
  'git://github.com/wincent/Command-T',
  'git://github.com/vim-scripts/grep.vim',
  'git://github.com/vim-scripts/vimgrep.vim',
  'git://github.com/tpope/vim-endwise',
  'git://github.com/Keithbsmiley/rspec.vim',
  'git://github.com/saks/Specky',
  'git://github.com/scrooloose/syntastic',
  'git://github.com/elzr/vim-json',
  'git://github.com/bkad/CamelCaseMotion',
  'git://github.com/bling/vim-airline',
  'git://github.com/jrhorn424/vim-multiple-cursors',
  #'git://github.com/gregsexton/gitv',
]

git_keep = []

bundles_dir = File.join(File.dirname(__FILE__), 'bundle')

FileUtils.mkdir bundles_dir unless File.exists?(bundles_dir)
FileUtils.cd(bundles_dir)

puts "trashing everything..."
Dir['*'].each {|d| FileUtils.rm_rf d unless git_keep.include?(d) }

puts "fetching plugins..."
git_bundles.each do |url|
  dir = url.split('/').last

  puts "  Unpacking #{url} into #{dir}"
  %x{git clone #{url} #{dir}}
  FileUtils.rm_rf File.join(dir, ".git")
end

puts "compiling command-t..."

environment = 'ARCHFLAGS="-Wno-error=unused-command-line-argument-hard-error-in-future"'
command_t_path = File.join 'Command-T/ruby/command-t'
rvm_init_script = 'source $HOME/.zshrc && rvm use 2.0.0'
command_t_build_script = 'bundle && ruby extconf.rb && make'
puts %x{zsh -c 'cd #{command_t_path} && #{rvm_init_script} && #{environment} #{command_t_build_script}'}
